"""
4.2 Python sqlite3: inventory_repository.py
Repository pattern implementation for inventory items.
Features parameterized SQL queries, row mapping to dataclasses, and strict error handling.
"""

from dataclasses import asdict, dataclass
from pathlib import Path
import sqlite3
import sys

# Support direct and package execution
CURRENT_DIR = Path(__file__).resolve().parent
if str(CURRENT_DIR) not in sys.path:
    sys.path.insert(0, str(CURRENT_DIR))

from db_connection import configure_connection


@dataclass
class InventoryItem:
    id: int | None
    sku: str
    name: str
    category: str
    quantity: int
    unit_price: float

    @classmethod
    def from_row(cls, row: sqlite3.Row | tuple) -> "InventoryItem":
        """Maps a sqlite3 row to an InventoryItem dataclass instance."""
        if isinstance(row, sqlite3.Row):
            return cls(
                id=row["id"],
                sku=row["sku"],
                name=row["name"],
                category=row["category"],
                quantity=row["quantity"],
                unit_price=float(row["unit_price"]),
            )
        return cls(row[0], row[1], row[2], row[3], row[4], float(row[5]))

    def to_dict(self) -> dict:
        return asdict(self)


class InventoryRepository:
    """Data access repository for inventory records using parameterized queries."""

    SCHEMA_SQL = """
    CREATE TABLE IF NOT EXISTS inventory_items (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        sku TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        category TEXT NOT NULL,
        quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
        unit_price REAL NOT NULL CHECK (unit_price >= 0)
    );
    """

    def __init__(self, connection: sqlite3.Connection):
        self.conn = configure_connection(connection)
        self._ensure_schema()

    def _ensure_schema(self) -> None:
        """Initializes the table structure if missing."""
        self.conn.execute(self.SCHEMA_SQL)
        self.conn.commit()

    def create(self, item: InventoryItem) -> InventoryItem:
        """
        Inserts a new inventory item.
        Uses parameterized query (?, ?, ...) to prevent SQL injection.
        Returns the updated InventoryItem with its autogenerated ID.
        """
        sql = """
            INSERT INTO inventory_items (sku, name, category, quantity, unit_price)
            VALUES (?, ?, ?, ?, ?);
        """
        cursor = self.conn.cursor()
        try:
            cursor.execute(sql, (item.sku, item.name, item.category, item.quantity, item.unit_price))
            self.conn.commit()
            item.id = cursor.lastrowid
            return item
        except sqlite3.IntegrityError as err:
            self.conn.rollback()
            raise ValueError(f"Failed to create item '{item.sku}': {err}") from err

    def get_by_id(self, item_id: int) -> InventoryItem | None:
        """Retrieves a single item by primary key."""
        sql = "SELECT id, sku, name, category, quantity, unit_price FROM inventory_items WHERE id = ?;"
        cursor = self.conn.cursor()
        cursor.execute(sql, (item_id,))
        row = cursor.fetchone()
        return InventoryItem.from_row(row) if row else None

    def get_by_sku(self, sku: str) -> InventoryItem | None:
        """Retrieves a single item by SKU."""
        sql = "SELECT id, sku, name, category, quantity, unit_price FROM inventory_items WHERE sku = ?;"
        cursor = self.conn.cursor()
        cursor.execute(sql, (sku,))
        row = cursor.fetchone()
        return InventoryItem.from_row(row) if row else None

    def list_all(self, limit: int = 100, offset: int = 0) -> list[InventoryItem]:
        """Returns all inventory items with pagination."""
        sql = """
            SELECT id, sku, name, category, quantity, unit_price
            FROM inventory_items
            ORDER BY id ASC
            LIMIT ? OFFSET ?;
        """
        cursor = self.conn.cursor()
        cursor.execute(sql, (limit, offset))
        return [InventoryItem.from_row(row) for row in cursor.fetchall()]

    def update(self, item: InventoryItem) -> bool:
        """
        Updates an existing inventory record.
        Returns True if a record was updated, False if ID was not found.
        """
        if item.id is None:
            raise ValueError("Cannot update an item without a valid ID.")

        sql = """
            UPDATE inventory_items
            SET sku = ?, name = ?, category = ?, quantity = ?, unit_price = ?
            WHERE id = ?;
        """
        cursor = self.conn.cursor()
        try:
            cursor.execute(sql, (item.sku, item.name, item.category, item.quantity, item.unit_price, item.id))
            self.conn.commit()
            return cursor.rowcount > 0
        except sqlite3.IntegrityError as err:
            self.conn.rollback()
            raise ValueError(f"Update failed for item ID {item.id}: {err}") from err

    def delete(self, item_id: int) -> bool:
        """
        Deletes a record by ID.
        Returns True if row was deleted, False otherwise.
        """
        sql = "DELETE FROM inventory_items WHERE id = ?;"
        cursor = self.conn.cursor()
        cursor.execute(sql, (item_id,))
        self.conn.commit()
        return cursor.rowcount > 0


if __name__ == "__main__":
    conn = sqlite3.connect(":memory:")
    repo = InventoryRepository(conn)

    # 1. Create items
    item1 = repo.create(InventoryItem(None, "LAP-01", "ThinkPad T14", "Computers", 10, 1150.00))
    item2 = repo.create(InventoryItem(None, "MOU-01", "Logitech MX Master", "Accessories", 25, 99.00))
    print(f"Created items: ID {item1.id}, ID {item2.id}")

    # 2. Read by SKU
    retrieved = repo.get_by_sku("LAP-01")
    print(f"Retrieved: {retrieved}")

    # 3. Update item
    if retrieved:
        retrieved.quantity = 14
        repo.update(retrieved)
        print(f"Updated quantity: {repo.get_by_id(retrieved.id).quantity}")

    # 4. List all
    print(f"Total items in repository: {len(repo.list_all())}")

    # 5. Delete item
    repo.delete(item2.id)
    print(f"Remaining items after deletion: {len(repo.list_all())}")

    conn.close()
